openapi: 3.2.0
info:
  version: '4.0'
  title: FlyerKit Copyright API
  description: An API to access Flipp's publication data for use in your applications.
servers:
- url: https://api.flipp.com/flyerkit/v4.0
tags:
- name: copyright
paths:
  /copyright:
    get:
      summary: Returns Flipp copyright
      tags:
      - copyright
      responses:
        '200':
          description: Copyright response
      operationId: getCopyright
      x-operation-id-source: derived
